export function mainForm(_this) {
  return {
    submitBtn: false,
    emptyBtn: false,
    labelWidth: 120,
    column: [
      {
        label: "缸号",
        tip: "Mã vải",
        prop: "vatNo",
        span: 6,
        placeholder: " ",
      },
    ]
  };
}

export function mainCrud(_this) {
  return {
    menu: false,
    addBtn: false,
    border: true,
    highlightCurrentRow: true,
    height: "calc(100vh - 215px)",
    refreshBtn: false,
    columnBtn: false,
    page: true,
    labelPosition: "top",
    labelWidth: 150,
    column: [
      {
        label: "#",
        prop: "index",
        width: 50,
        align: "center",
        display: false,
        fixed: "left"
      },

      {
        label: "缸号",
        prop: "vatNo",
        width: 170,
        align: "left",
        fixed: "left",
        display: false
      },
      {
        label: '备布',
        fixed: "left",
        display: true,
        children: [
          {
            label: "实际",
            prop: "calicoWeight",
            width: 120,
            align: "center",
            fixed: "left",
            display: false,
            overHidden: true,
          },
          {
            label: "计划",
            prop: "clothWeight",
            width: 120,
            align: "center",
            fixed: "left",
            display: false,
            overHidden: true,
          },
        ],
      },

      {
        label: '生控',
        display: true,
        children: [
          {
            label: "初始工作量",
            prop: "skStart",
            width: 120,
            align: "left",
            display: false,
            overHidden: true,
          },
          {
            label: "发单工作量",
            prop: "skSndWrk",
            width: 120,
            align: "left",
            display: false,
            overHidden: true,
          },
          {
            label: "发单次数",
            prop: "skSndCount",
            width: 120,
            align: "left",
            display: false,
            overHidden: true,
          },
          {
            label: "收单工作量",
            prop: "skRcvWrk",
            width: 120,
            align: "left",
            display: false,
            overHidden: true,
          },
          {
            label: "收单次数",
            prop: "skRcvCount",
            width: 120,
            align: "left",
            display: false,
            overHidden: true,
          },
        ],
      },
      {
        label: '批色',
        display: true,
        children: [
          {
            label: "初始工作量",
            prop: "psStart",
            width: 120,
            align: "left",
            display: false,
            overHidden: true,
          },
          {
            label: "发单工作量",
            prop: "psSndWrk",
            width: 120,
            align: "left",
            display: false,
            overHidden: true,
          },
          {
            label: "发单次数",
            prop: "psSndCount",
            width: 120,
            align: "left",
            display: false,
            overHidden: true,
          },
          {
            label: "收单工作量",
            prop: "psRcvWrk",
            width: 120,
            align: "left",
            display: false,
            overHidden: true,
          },
          {
            label: "收单次数",
            prop: "psRcvCount",
            width: 120,
            align: "left",
            display: false,
            overHidden: true,
          },
        ],
      },
      {
        label: '定型',
        display: true,
        children: [
          {
            label: "初始工作量",
            prop: "dxStart",
            width: 120,
            align: "left",
            display: false,
            overHidden: true,
          },
          {
            label: "发单工作量",
            prop: "dxSndWrk",
            width: 120,
            align: "left",
            display: false,
            overHidden: true,
          },
          {
            label: "发单次数",
            prop: "dxSndCount",
            width: 120,
            align: "left",
            display: false,
            overHidden: true,
          },
          {
            label: "收单工作量",
            prop: "dxRcvWrk",
            width: 120,
            align: "left",
            display: false,
            overHidden: true,
          },
          {
            label: "收单次数",
            prop: "dxRcvCount",
            width: 120,
            align: "left",
            display: false,
            overHidden: true,
          },
        ],
      },
      {
        label: '染色',
        display: true,
        children: [
          {
            label: "初始工作量",
            prop: "rsStart",
            width: 120,
            align: "left",
            display: false,
            overHidden: true,
          },
          {
            label: "发单工作量",
            prop: "rsSndWrk",
            width: 120,
            align: "left",
            display: false,
            overHidden: true,
          },
          {
            label: "发单次数",
            prop: "rsSndCount",
            width: 120,
            align: "left",
            display: false,
            overHidden: true,
          },
          {
            label: "收单工作量",
            prop: "rsRcvWrk",
            width: 120,
            align: "left",
            display: false,
            overHidden: true,
          },
          {
            label: "收单次数",
            prop: "rsRcvCount",
            width: 120,
            align: "left",
            display: false,
            overHidden: true,
          },
        ],
      },
      {
        label: '后整',
        display: true,
        children: [
          {
            label: "初始工作量",
            prop: "hzStart",
            width: 120,
            align: "left",
            display: false,
            overHidden: true,
          },
          {
            label: "发单工作量",
            prop: "hzSndWrk",
            width: 120,
            align: "left",
            display: false,
            overHidden: true,
          },
          {
            label: "发单次数",
            prop: "hzSndCount",
            width: 120,
            align: "left",
            display: false,
            overHidden: true,
          },
          {
            label: "收单工作量",
            prop: "hzRcvWrk",
            width: 120,
            align: "left",
            display: false,
            overHidden: true,
          },
          {
            label: "收单次数",
            prop: "hzRcvCount",
            width: 120,
            align: "left",
            display: false,
            overHidden: true,
          },
        ],
      },
      {
        label: 'QC',
        display: true,
        children: [
          {
            label: "初始工作量",
            prop: "qcStart",
            width: 120,
            align: "left",
            display: false,
            overHidden: true,
          },
          {
            label: "发单工作量",
            prop: "qcSndWrk",
            width: 120,
            align: "left",
            display: false,
            overHidden: true,
          },
          {
            label: "发单次数",
            prop: "qcSndCount",
            width: 120,
            align: "left",
            display: false,
            overHidden: true,
          },
          {
            label: "收单工作量",
            prop: "qcRcvWrk",
            width: 120,
            align: "left",
            display: false,
            overHidden: true,
          },
          {
            label: "收单次数",
            prop: "qcRcvCount",
            width: 120,
            align: "left",
            display: false,
            overHidden: true,
          },
        ],
      },
      {
        label: 'QA',
        display: true,
        children: [
          {
            label: "初始工作量",
            prop: "qaStart",
            width: 120,
            align: "left",
            display: false,
            overHidden: true,
          },
          {
            label: "发单工作量",
            prop: "qaSndWrk",
            width: 120,
            align: "left",
            display: false,
            overHidden: true,
          },
          {
            label: "发单次数",
            prop: "qaSndCount",
            width: 120,
            align: "left",
            display: false,
            overHidden: true,
          },
          {
            label: "收单工作量",
            prop: "qaRcvWrk",
            width: 120,
            align: "left",
            display: false,
            overHidden: true,
          },
          {
            label: "收单次数",
            prop: "qaRcvCount",
            width: 120,
            align: "left",
            display: false,
            overHidden: true,
          },
        ],
      },
      {
        label: '仓库',
        display: true,
        children: [
          {
            label: "初始工作量",
            prop: "ckStart",
            width: 120,
            align: "left",
            display: false,
            overHidden: true,
          },
          {
            label: "发单工作量",
            prop: "ckSndWrk",
            width: 120,
            align: "left",
            display: false,
            overHidden: true,
          },
          {
            label: "发单次数",
            prop: "ckSndCount",
            width: 120,
            align: "left",
            display: false,
            overHidden: true,
          },
          {
            label: "收单工作量",
            prop: "ckRcvWrk",
            width: 120,
            align: "left",
            display: false,
            overHidden: true,
          },
          {
            label: "收单次数",
            prop: "ckRcvCount",
            width: 120,
            align: "left",
            display: false,
            overHidden: true,
          },

        ],

      },
      {
        label: "开始时间",
        prop: "startTime",
        width: 170,
        align: "left",
        fixed: "right",
        display: false
      },
      {
        label: "结束时间",
        prop: "endTime",
        width: 170,
        align: "left",
        fixed: "right",
        display: false
      },
    ]
  };
}
